[package]
authors = ["The Nu Project Contributors"]
description = "Nushell std lib commands"
edition = "2018"
license = "MIT"
name = "nu-commands-std"
version = "0.25.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
